import dotenv from 'dotenv';

import { Blockchain } from '../types/configs';
import { AddressZero } from './constants';
import { ChainNames } from './names';

// global env and configurations
dotenv.config();

export const BlockchainConfigs: { [key: string]: Blockchain } = {
  [ChainNames.ethereum]: {
    name: ChainNames.ethereum,
    family: 'evm',
    chainId: 1,
    nodeRpc: String(process.env.BUNNYBOARD_ETHEREUM_NODE),
    nativeToken: {
      chain: ChainNames.ethereum,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.arbitrum]: {
    name: ChainNames.arbitrum,
    family: 'evm',
    chainId: 42161,
    nodeRpc: String(process.env.BUNNYBOARD_ARBITRUM_NODE),
    nativeToken: {
      chain: ChainNames.arbitrum,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.base]: {
    name: ChainNames.base,
    family: 'evm',
    chainId: 8453,
    nodeRpc: String(process.env.BUNNYBOARD_BASE_NODE),
    nativeToken: {
      chain: ChainNames.base,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.optimism]: {
    name: ChainNames.optimism,
    family: 'evm',
    chainId: 10,
    nodeRpc: String(process.env.BUNNYBOARD_OPTIMISM_NODE),
    nativeToken: {
      chain: ChainNames.optimism,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.polygon]: {
    name: ChainNames.polygon,
    family: 'evm',
    chainId: 137,
    nodeRpc: String(process.env.BUNNYBOARD_POLYGON_NODE),
    nativeToken: {
      chain: ChainNames.polygon,
      address: AddressZero,
      symbol: 'MATIC',
      decimals: 18,
    },
  },
  [ChainNames.bnbchain]: {
    name: ChainNames.bnbchain,
    family: 'evm',
    chainId: 56,
    nodeRpc: String(process.env.BUNNYBOARD_BNBCHAIN_NODE),
    nativeToken: {
      chain: ChainNames.bnbchain,
      address: AddressZero,
      symbol: 'BNB',
      decimals: 18,
    },
  },
  [ChainNames.avalanche]: {
    name: ChainNames.avalanche,
    family: 'evm',
    chainId: 43114,
    nodeRpc: String(process.env.BUNNYBOARD_AVALANCHE_NODE),
    nativeToken: {
      chain: ChainNames.avalanche,
      address: AddressZero,
      symbol: 'AVAX',
      decimals: 18,
    },
  },
  [ChainNames.fantom]: {
    name: ChainNames.fantom,
    family: 'evm',
    chainId: 250,
    nodeRpc: String(process.env.BUNNYBOARD_FANTOM_NODE),
    nativeToken: {
      chain: ChainNames.fantom,
      address: AddressZero,
      symbol: 'FTM',
      decimals: 18,
    },
  },
  [ChainNames.metis]: {
    name: ChainNames.metis,
    family: 'evm',
    chainId: 1088,
    nodeRpc: String(process.env.BUNNYBOARD_METIS_NODE),
    nativeToken: {
      chain: ChainNames.metis,
      address: AddressZero,
      symbol: 'METIS',
      decimals: 18,
    },
  },
  [ChainNames.gnosis]: {
    name: ChainNames.gnosis,
    family: 'evm',
    chainId: 100,
    nodeRpc: String(process.env.BUNNYBOARD_GNOSIS_NODE),
    nativeToken: {
      chain: ChainNames.gnosis,
      address: AddressZero,
      symbol: 'xDAI',
      decimals: 18,
    },
  },
  [ChainNames.scroll]: {
    name: ChainNames.scroll,
    family: 'evm',
    chainId: 534352,
    nodeRpc: String(process.env.BUNNYBOARD_SCROLL_NODE),
    nativeToken: {
      chain: ChainNames.scroll,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.blast]: {
    name: ChainNames.blast,
    family: 'evm',
    chainId: 81457,
    nodeRpc: String(process.env.BUNNYBOARD_BLAST_NODE),
    nativeToken: {
      chain: ChainNames.blast,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.linea]: {
    name: ChainNames.linea,
    family: 'evm',
    chainId: 59144,
    nodeRpc: String(process.env.BUNNYBOARD_LINEA_NODE),
    nativeToken: {
      chain: ChainNames.linea,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.zksync]: {
    name: ChainNames.zksync,
    family: 'evm',
    chainId: 324,
    nodeRpc: String(process.env.BUNNYBOARD_ZKSYNC_NODE),
    nativeToken: {
      chain: ChainNames.zksync,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.mode]: {
    name: ChainNames.mode,
    family: 'evm',
    chainId: 34443,
    nodeRpc: String(process.env.BUNNYBOARD_MODE_NODE),
    nativeToken: {
      chain: ChainNames.mode,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.manta]: {
    name: ChainNames.manta,
    family: 'evm',
    chainId: 169,
    nodeRpc: String(process.env.BUNNYBOARD_MANTA_NODE),
    nativeToken: {
      chain: ChainNames.manta,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.aurora]: {
    name: ChainNames.aurora,
    family: 'evm',
    chainId: 1313161554,
    nodeRpc: String(process.env.BUNNYBOARD_AURORA_NODE),
    nativeToken: {
      chain: ChainNames.aurora,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.celo]: {
    name: ChainNames.celo,
    family: 'evm',
    chainId: 42220,
    nodeRpc: String(process.env.BUNNYBOARD_CELO_NODE),
    nativeToken: {
      chain: ChainNames.celo,
      address: AddressZero,
      symbol: 'CELO',
      decimals: 18,
    },
  },
  [ChainNames.mantle]: {
    name: ChainNames.mantle,
    family: 'evm',
    chainId: 5000,
    nodeRpc: String(process.env.BUNNYBOARD_MANTLE_NODE),
    nativeToken: {
      chain: ChainNames.mantle,
      address: AddressZero,
      symbol: 'MNT',
      decimals: 18,
    },
  },
  [ChainNames.polygonzkevm]: {
    name: ChainNames.polygonzkevm,
    family: 'evm',
    chainId: 1101,
    nodeRpc: String(process.env.BUNNYBOARD_POLYGONZKEVM_NODE),
    nativeToken: {
      chain: ChainNames.polygonzkevm,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.zora]: {
    name: ChainNames.zora,
    family: 'evm',
    chainId: 7777777,
    nodeRpc: String(process.env.BUNNYBOARD_ZORA_NODE),
    nativeToken: {
      chain: ChainNames.zora,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.merlin]: {
    name: ChainNames.merlin,
    family: 'evm',
    chainId: 4200,
    nodeRpc: String(process.env.BUNNYBOARD_MERLIN_NODE),
    nativeToken: {
      chain: ChainNames.merlin,
      address: AddressZero,
      symbol: 'BTC',
      decimals: 18,
    },
  },
  [ChainNames.zklinknova]: {
    name: ChainNames.zklinknova,
    family: 'evm',
    chainId: 810180,
    nodeRpc: String(process.env.BUNNYBOARD_ZKLINKNOVA_NODE),
    nativeToken: {
      chain: ChainNames.zklinknova,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.cronos]: {
    name: ChainNames.cronos,
    family: 'evm',
    chainId: 25,
    nodeRpc: String(process.env.BUNNYBOARD_CRONOS_NODE),
    nativeToken: {
      chain: ChainNames.cronos,
      address: AddressZero,
      symbol: 'CRO',
      decimals: 18,
    },
  },
  [ChainNames.moonbeam]: {
    name: ChainNames.moonbeam,
    family: 'evm',
    chainId: 1284,
    nodeRpc: String(process.env.BUNNYBOARD_MOONBEAM_NODE),
    nativeToken: {
      chain: ChainNames.moonbeam,
      address: AddressZero,
      symbol: 'GLMR',
      decimals: 18,
    },
  },
  [ChainNames.moonriver]: {
    name: ChainNames.moonriver,
    family: 'evm',
    chainId: 1285,
    nodeRpc: String(process.env.BUNNYBOARD_MOONRIVER_NODE),
    nativeToken: {
      chain: ChainNames.moonriver,
      address: AddressZero,
      symbol: 'MOVR',
      decimals: 18,
    },
  },
  [ChainNames.core]: {
    name: ChainNames.core,
    family: 'evm',
    chainId: 1116,
    nodeRpc: String(process.env.BUNNYBOARD_CORE_NODE),
    nativeToken: {
      chain: ChainNames.core,
      address: AddressZero,
      symbol: 'CORE',
      decimals: 18,
    },
  },
  [ChainNames.bitlayer]: {
    name: ChainNames.bitlayer,
    family: 'evm',
    chainId: 200901,
    nodeRpc: String(process.env.BUNNYBOARD_BITLAYER_NODE),
    nativeToken: {
      chain: ChainNames.bitlayer,
      address: AddressZero,
      symbol: 'BTC',
      decimals: 18,
    },
  },
  [ChainNames.taiko]: {
    name: ChainNames.taiko,
    family: 'evm',
    chainId: 167000,
    nodeRpc: String(process.env.BUNNYBOARD_TAIKO_NODE),
    nativeToken: {
      chain: ChainNames.taiko,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.seievm]: {
    name: ChainNames.seievm,
    family: 'evm',
    chainId: 1329,
    nodeRpc: String(process.env.BUNNYBOARD_SEIEVM_NODE),
    nativeToken: {
      chain: ChainNames.seievm,
      address: AddressZero,
      symbol: 'SEI',
      decimals: 18,
    },
  },
  [ChainNames.bob]: {
    name: ChainNames.bob,
    family: 'evm',
    chainId: 60808,
    nodeRpc: String(process.env.BUNNYBOARD_BOB_NODE),
    nativeToken: {
      chain: ChainNames.bob,
      address: AddressZero,
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [ChainNames.bsquared]: {
    name: ChainNames.bsquared,
    family: 'evm',
    chainId: 223,
    nodeRpc: String(process.env.BUNNYBOARD_BSQUARED_NODE),
    nativeToken: {
      chain: ChainNames.bsquared,
      address: AddressZero,
      symbol: 'BTC',
      decimals: 18,
    },
  },
  [ChainNames.ronin]: {
    name: ChainNames.ronin,
    family: 'evm',
    chainId: 2020,
    nodeRpc: String(process.env.BUNNYBOARD_RONIN_NODE),
    nativeToken: {
      chain: ChainNames.ronin,
      address: AddressZero,
      symbol: 'RON',
      decimals: 18,
    },
  },
  [ChainNames.fraxtal]: {
    name: ChainNames.fraxtal,
    family: 'evm',
    chainId: 252,
    nodeRpc: String(process.env.BUNNYBOARD_FRAXTAL_NODE),
    nativeToken: {
      chain: ChainNames.fraxtal,
      address: AddressZero,
      symbol: 'frxETH',
      decimals: 18,
    },
  },
};
