import { ChainConfig, ChainFamilies } from '../types/base';
import { ChainNames } from './names';

export const ChainBoardConfigs: { [key: string]: ChainConfig } = {
  [ChainNames.ethereum]: {
    chain: ChainNames.ethereum,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://eth.llamarpc.com',
      'https://rpc.mevblocker.io',
      'https://rpc.mevblocker.io/fast',
      'https://eth.meowrpc.com',
      'https://rpc.flashbots.net',
      'https://eth-pokt.nodies.app',
      'https://rpc.ankr.com/eth',
      'https://ethereum.blockpi.network/v1/rpc/public',
    ],
  },
  [ChainNames.arbitrum]: {
    chain: ChainNames.arbitrum,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://arb1.arbitrum.io/rpc',
      'https://arb-pokt.nodies.app',
      'https://rpc.ankr.com/arbitrum',
      'https://arbitrum-one.publicnode.com',
      'https://1rpc.io/arb',
      'https://arbitrum.llamarpc.com',
      'https://arbitrum.blockpi.network/v1/rpc/public',
    ],
  },
  [ChainNames.bnbchain]: {
    chain: ChainNames.bnbchain,
    family: ChainFamilies.evm,
    nativeToken: 'BNB',
    nodeRpcs: [
      'https://bscrpc.com',
      'https://binance.llamarpc.com',
      'https://rpc.ankr.com/bsc',
      'https://bsc-pokt.nodies.app',
      'https://bsc-dataseed.bnbchain.org',
      'https://bsc-dataseed1.ninicoin.io',
      'https://1rpc.io/bnb',
      'https://bsc-dataseed4.defibit.io',
      'https://bsc-dataseed3.defibit.io',
    ],
  },
  [ChainNames.polygon]: {
    chain: ChainNames.polygon,
    family: ChainFamilies.evm,
    nativeToken: 'POL',
    nodeRpcs: [
      'https://polygon.llamarpc.com',
      'https://rpc.ankr.com/polygon',
      'https://polygon-rpc.com',
      'https://polygon-pokt.nodies.app',
      'https://1rpc.io/matic',
      'https://polygon.blockpi.network/v1/rpc/public',
      'https://polygon.rpc.blxrbdn.com',
      'https://polygon.gateway.tenderly.co',
      'https://polygon.meowrpc.com',
    ],
  },
  [ChainNames.fantom]: {
    chain: ChainNames.fantom,
    family: ChainFamilies.evm,
    nativeToken: 'FTM',
    nodeRpcs: [
      'https://rpc.ftm.tools',
      'https://rpcapi.fantom.network',
      'https://rpc.ankr.com/fantom',
      'https://rpc.fantom.network',
      'https://rpc2.fantom.network',
      'https://rpc3.fantom.network',
    ],
  },
  [ChainNames.optimism]: {
    chain: ChainNames.optimism,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://optimism.llamarpc.com',
      'https://mainnet.optimism.io',
      'https://rpc.ankr.com/optimism',
      'https://optimism-mainnet.public.blastapi.io',
      'https://1rpc.io/op',
      'https://op-pokt.nodies.app',
      'https://optimism.api.onfinality.io/public',
      'https://optimism.blockpi.network/v1/rpc/public',
      'https://optimism-rpc.publicnode.com',
      'https://optimism.meowrpc.com',
      'https://optimism.gateway.tenderly.co',
      'https://gateway.tenderly.co/public/optimism',
    ],
  },
  [ChainNames.base]: {
    chain: ChainNames.base,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://base.llamarpc.com',
      'https://mainnet.base.org',
      'https://developer-access-mainnet.base.org',
      'https://base.blockpi.network/v1/rpc/public',
      'https://1rpc.io/base',
      'https://base-pokt.nodies.app',
      'https://base.meowrpc.com',
      'https://base-mainnet.public.blastapi.io',
      'https://base.gateway.tenderly.co',
      'https://gateway.tenderly.co/public/base',
    ],
  },
  [ChainNames.avalanche]: {
    chain: ChainNames.avalanche,
    family: ChainFamilies.evm,
    nativeToken: 'AVAX',
    nodeRpcs: [
      'https://api.avax.network/ext/bc/C/rpc',
      'https://avalanche.public-rpc.com',
      'https://rpc.ankr.com/avalanche',
      'https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc',
      'https://avalanche-c-chain-rpc.publicnode.com',
      'https://avalanche.blockpi.network/v1/rpc/public',
      'https://avax-pokt.nodies.app/ext/bc/C/rpc',
      'https://avalanche-mainnet.gateway.tenderly.co',
    ],
  },
  [ChainNames.blast]: {
    chain: ChainNames.blast,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://rpc.blast.io',
      'https://blast.din.dev/rpc',
      'https://blastl2-mainnet.public.blastapi.io',
      'https://blast.blockpi.network/v1/rpc/public',
      'https://rpc.ankr.com/blast',
      'https://blast-rpc.publicnode.com',
      'https://blast.gateway.tenderly.co',
    ],
  },
  [ChainNames.linea]: {
    chain: ChainNames.linea,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://rpc.linea.build',
      'https://linea.blockpi.network/v1/rpc/public',
      'https://linea-rpc.publicnode.com',
      'https://1rpc.io/linea',
    ],
  },
  [ChainNames.scroll]: {
    chain: ChainNames.scroll,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://rpc.scroll.io',
      'https://scroll-mainnet.public.blastapi.io',
      'https://scroll.blockpi.network/v1/rpc/public',
      'https://1rpc.io/scroll',
      'https://scroll.api.onfinality.io/public',
      'https://rpc.ankr.com/scroll',
      'https://scroll-mainnet.chainstacklabs.com',
      'https://scroll-rpc.publicnode.com',
    ],
  },
  [ChainNames.mantle]: {
    chain: ChainNames.mantle,
    family: ChainFamilies.evm,
    nativeToken: 'MNT',
    nodeRpcs: [
      'https://rpc.mantle.xyz',
      'https://mantle-mainnet.public.blastapi.io',
      'https://mantle-rpc.publicnode.com',
      'https://rpc.ankr.com/mantle',
      'https://1rpc.io/mantle',
      'https://mantle.api.onfinality.io/public',
    ],
  },
  [ChainNames.mode]: {
    chain: ChainNames.mode,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://mainnet.mode.network',
      'https://1rpc.io/mode',
      'https://mode.drpc.org',
      'https://mode.gateway.tenderly.co',
    ],
  },
  [ChainNames.fraxtal]: {
    chain: ChainNames.fraxtal,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: ['https://rpc.frax.com', 'https://fraxtal.drpc.org', 'https://fraxtal.gateway.tenderly.co'],
  },
  [ChainNames.lisk]: {
    chain: ChainNames.lisk,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: ['https://rpc.api.lisk.com', 'https://lisk.drpc.org', 'https://lisk.gateway.tenderly.co'],
  },
  [ChainNames.bob]: {
    chain: ChainNames.bob,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://rpc.gobob.xyz',
      'https://bob.drpc.org',
      'https://bob.gateway.tenderly.co',
      'https://bob-mainnet.public.blastapi.io',
    ],
  },
  [ChainNames.metis]: {
    chain: ChainNames.metis,
    family: ChainFamilies.evm,
    nativeToken: 'METIS',
    nodeRpcs: [
      'https://andromeda.metis.io/?owner=1088',
      'https://metis-mainnet.public.blastapi.io',
      'https://metis.api.onfinality.io/public',
      'https://metis-pokt.nodies.app',
      'https://metis.drpc.org',
    ],
  },
  [ChainNames.gnosis]: {
    chain: ChainNames.gnosis,
    family: ChainFamilies.evm,
    nativeToken: 'xDAI',
    nodeRpcs: [
      'https://rpc.gnosischain.com',
      'https://gnosis-pokt.nodies.app',
      'https://gnosis-mainnet.public.blastapi.io',
      'https://rpc.ankr.com/gnosis',
      'https://gnosis.blockpi.network/v1/rpc/public',
      'https://gnosis.api.onfinality.io/public',
      'https://gnosis.drpc.org',
      'https://endpoints.omniatech.io/v1/gnosis/mainnet/public',
      'https://gnosis-rpc.publicnode.com',
      'https://1rpc.io/gnosis',
    ],
  },
  [ChainNames.zksync]: {
    chain: ChainNames.zksync,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://mainnet.era.zksync.io',
      'https://zksync-era.blockpi.network/v1/rpc/public',
      'https://zksync.meowrpc.com',
      'https://zksync.drpc.org',
      'https://1rpc.io/zksync2-era',
      'https://endpoints.omniatech.io/v1/zksync-era/mainnet/public',
    ],
  },
  [ChainNames.celo]: {
    chain: ChainNames.celo,
    family: ChainFamilies.evm,
    nativeToken: 'CELO',
    nodeRpcs: [
      'https://forno.celo.org',
      'https://rpc.ankr.com/celo',
      'https://1rpc.io/celo',
      'https://celo.api.onfinality.io/public',
      'https://celo.drpc.org',
    ],
  },
  [ChainNames.polygonzkevm]: {
    chain: ChainNames.polygonzkevm,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://rpc.ankr.com/polygon_zkevm',
      'https://rpc.polygon-zkevm.gateway.fm',
      'https://1rpc.io/polygon/zkevm',
      'https://polygon-zkevm.blockpi.network/v1/rpc/public',
      'https://polygon-zkevm-mainnet.public.blastapi.io',
      'https://polygon-zkevm.drpc.org',
      'https://endpoints.omniatech.io/v1/polygon-zkevm/mainnet/public',
      'https://zkevm-rpc.com',
    ],
  },
  [ChainNames.merlin]: {
    chain: ChainNames.merlin,
    family: ChainFamilies.evm,
    nativeToken: 'BTC',
    nodeRpcs: ['https://rpc.merlinchain.io', 'https://merlin.blockpi.network/v1/rpc/public'],
  },
};
