import { ChainConfig, ChainFamilies } from '../types/base';
import { ChainNames } from './names';

export const ChainBoardConfigs: { [key: string]: ChainConfig } = {
  ethereum: {
    chain: ChainNames.ethereum,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://eth.llamarpc.com',
      'https://rpc.mevblocker.io',
      'https://rpc.mevblocker.io/fast',
      'https://eth.meowrpc.com',
      'https://rpc.flashbots.net',
      'https://eth-pokt.nodies.app',
      'https://rpc.ankr.com/eth',
      'https://ethereum.blockpi.network/v1/rpc/public',
    ],
  },
  arbitrum: {
    chain: ChainNames.arbitrum,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://arb1.arbitrum.io/rpc',
      'https://arb-pokt.nodies.app',
      'https://rpc.ankr.com/arbitrum',
      'https://arbitrum-one.publicnode.com',
      'https://1rpc.io/arb',
      'https://arbitrum.llamarpc.com',
      'https://arbitrum.blockpi.network/v1/rpc/public',
    ],
  },
  bnbchain: {
    chain: ChainNames.bnbchain,
    family: ChainFamilies.evm,
    nativeToken: 'BNB',
    nodeRpcs: [
      'https://bscrpc.com',
      'https://binance.llamarpc.com',
      'https://rpc.ankr.com/bsc',
      'https://bsc-pokt.nodies.app',
      'https://bsc-dataseed.bnbchain.org',
      'https://bsc-dataseed1.ninicoin.io',
      'https://1rpc.io/bnb',
      'https://bsc-dataseed4.defibit.io',
      'https://bsc-dataseed3.defibit.io',
    ],
  },
  polygon: {
    chain: ChainNames.polygon,
    family: ChainFamilies.evm,
    nativeToken: 'POL',
    nodeRpcs: [
      'https://polygon.llamarpc.com',
      'https://rpc.ankr.com/polygon',
      'https://polygon-rpc.com',
      'https://polygon-pokt.nodies.app',
      'https://1rpc.io/matic',
      'https://polygon.blockpi.network/v1/rpc/public',
      'https://polygon.rpc.blxrbdn.com',
      'https://polygon.gateway.tenderly.co',
      'https://polygon.meowrpc.com',
    ],
  },
  fantom: {
    chain: ChainNames.fantom,
    family: ChainFamilies.evm,
    nativeToken: 'FTM',
    nodeRpcs: [
      'https://rpc.ftm.tools',
      'https://rpcapi.fantom.network',
      'https://rpc.ankr.com/fantom',
      'https://rpc.fantom.network',
      'https://rpc2.fantom.network',
      'https://rpc3.fantom.network',
    ],
  },
  optimism: {
    chain: ChainNames.optimism,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://optimism.llamarpc.com',
      'https://mainnet.optimism.io',
      'https://rpc.ankr.com/optimism',
      'https://optimism-mainnet.public.blastapi.io',
      'https://1rpc.io/op',
      'https://op-pokt.nodies.app',
      'https://optimism.api.onfinality.io/public',
      'https://optimism.blockpi.network/v1/rpc/public',
      'https://optimism-rpc.publicnode.com',
      'https://optimism.meowrpc.com',
      'https://optimism.gateway.tenderly.co',
      'https://gateway.tenderly.co/public/optimism',
    ],
  },
  base: {
    chain: ChainNames.base,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://base.llamarpc.com',
      'https://mainnet.base.org',
      'https://developer-access-mainnet.base.org',
      'https://base.blockpi.network/v1/rpc/public',
      'https://1rpc.io/base',
      'https://base-pokt.nodies.app',
      'https://base.meowrpc.com',
      'https://base-mainnet.public.blastapi.io',
      'https://base.gateway.tenderly.co',
      'https://gateway.tenderly.co/public/base',
    ],
  },
  avalanche: {
    chain: ChainNames.avalanche,
    family: ChainFamilies.evm,
    nativeToken: 'AVAX',
    nodeRpcs: [
      'https://api.avax.network/ext/bc/C/rpc',
      'https://avalanche.public-rpc.com',
      'https://rpc.ankr.com/avalanche',
      'https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc',
      'https://avalanche-c-chain-rpc.publicnode.com',
      'https://avalanche.blockpi.network/v1/rpc/public',
      'https://avax-pokt.nodies.app/ext/bc/C/rpc',
      'https://avalanche-mainnet.gateway.tenderly.co',
    ],
  },
  blast: {
    chain: ChainNames.blast,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://rpc.blast.io',
      'https://blast.din.dev/rpc',
      'https://blastl2-mainnet.public.blastapi.io',
      'https://blast.blockpi.network/v1/rpc/public',
      'https://rpc.ankr.com/blast',
      'https://blast-rpc.publicnode.com',
      'https://blast.gateway.tenderly.co',
    ],
  },
  linea: {
    chain: ChainNames.linea,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://rpc.linea.build',
      'https://linea.blockpi.network/v1/rpc/public',
      'https://linea-rpc.publicnode.com',
      'https://1rpc.io/linea',
    ],
  },
  scroll: {
    chain: ChainNames.scroll,
    family: ChainFamilies.evm,
    nativeToken: 'ETH',
    nodeRpcs: [
      'https://rpc.scroll.io',
      'https://scroll-mainnet.public.blastapi.io',
      'https://scroll.blockpi.network/v1/rpc/public',
      'https://1rpc.io/scroll',
      'https://scroll.api.onfinality.io/public',
      'https://rpc.ankr.com/scroll',
      'https://scroll-mainnet.chainstacklabs.com',
      'https://scroll-rpc.publicnode.com',
    ],
  },
  mantle: {
    chain: ChainNames.mantle,
    family: ChainFamilies.evm,
    nativeToken: 'MNT',
    nodeRpcs: [
      'https://rpc.mantle.xyz',
      'https://mantle-mainnet.public.blastapi.io',
      'https://mantle-rpc.publicnode.com',
      'https://rpc.ankr.com/mantle',
      'https://1rpc.io/mantle',
      'https://mantle.api.onfinality.io/public',
    ],
  },
};
